pipeline:
  name: check tag
  identifier: check_tag
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S123
        identifier: S123
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_112
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo 'hi new branch'
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
