pipeline:
  name: secretCheck
  identifier: secretCheck
  projectIdentifier: AmitTest
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: <+input>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  variables:
    - name: var1
      type: String
      description: ""
      required: false
      value: <+input>
  notificationRules:
    - name: xvxv
      identifier: xvxv
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Email
        spec:
          userGroups:
            - ug1
          recipients:
            - amit.singh@harness.io
      enabled: true
