pipeline:
  name: TestRemoteAmitNonDefault
  identifier: TestRemoteAmitNonDefault
  projectIdentifier: DoNotDelete_Brooke2
  orgIdentifier: Ng_Pipelines_K8s_Organisations
  tags: {}
  stages:
    - stage:
        name: s123
        identifier: s123
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: exit 0
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: s1
        identifier: s1
        tags: {}
        template:
          templateRef: stagetemp
          versionLabel: v1
          gitBranch: main
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
              service:
                serviceRef: <+pipeline.variables.dummyVar>
  variables:
    - name: dummyVar
      type: String
      description: ""
      required: false
      value: <+input>
